# Java的异常处理

## 异常简介

- 描述：java程序在运行期间出现的错误称为异常，类文件在编译时出现的错误称为语法错误

- 异常的继承关系：Throwable：Error、Exception

- 异常的类型

  - 检查性异常（checked exception）：
    程序在运行时可能产生的异常，所以在代码中必须完成异常处理，否则无法通过编译（非RuntimeException）

  - 非检查性异常（unchecked exception||RuntimeException）：
    程序在运行中可能产生异常，不是必须在程序中声明对异常的处理，不声明异常处理程序也可以编译通过

  - java中常遇到的异常
    非检查性异常：

    |         `非检查型异常`         |            描述             |
    | :----------------------------: | :-------------------------: |
    |        RuntimeException        | java.lang包中多数异常的基类 |
    |      ArithmeticException       |          算数异常           |
    | ArrayIndexOutOfBoundsException |      数组下标越界异常       |
    |      NullPointerException      |         空指针异常          |

    |       检查型异常       |                           描述                           |
    | :--------------------: | :------------------------------------------------------: |
    | ClassNotFoundException |                找不到生成对象的类文件异常                |
    |      IOException       | IO异常的基类（凡是和IO流操作相关的异常都是来自于该基类） |
    | NoSuchMethodException  |                   访问方法不存在的异常                   |

  - 异常的处理机制

    - 描述：java中异常的处理方式分为两种方式
    - 自行处理：
      将可能产生异常的代码封装到try块内，而相应的处理过程封装到catch块内
    - 回避异常：
      在方法声明中，通过关键字throws抛出可能存在的异常，通知后续的使用者如果发生异常了，由后续使用者处理；
    
  - 异常处理的机制
  
    - 异常处理的语法格式
      try{
      		可能产生异常的代码;
      }catch(异常类 对象名){
      		异常相关的提示信息（异常的处理）
      }
    - 说明：
      jdk7版本开始，catch块可以同时定义多个，catch的小括号中可以同时定义或描述多个异常类，每个类之间用|分隔（单个catch可以处理多个异常），且不能出现父子关系
      当catch同时出现多个时，catch中所描述的异常类一定是满足从小到大（如果多个catch中出现父与子的关系，一定是先子后父）
    - finally处理机制
      描述：finally出现在try{}catch(){}语句之后，该关键字所封装的代码不管是否被捕获，总是要执行的；通常在开发中该关键字主要用来封装资源的释放；即便try{}catch(){}语句中出现return、break，finally所描述的程序也必须执行，只有当系统退出时（System.exit(0)），finally所封装的语句才不执行
    - throws关键字使用 
      描述：铜鼓throws关键字在方法后抛出异常（回避异常），该关键字可以由逗号分隔多个异常；后续使用者对throws抛出的异常进行处理（谁调用该方法，谁就处理方法抛出的异常，通过try..catch...）
  
  - 自定义异常
    如果java提供的异常类满足不了开发使用，则需要开发者自定义封装异常类，需要遵守规则，该自定义的异常类必须是Exception的子类（或者是继承Exception的其他子类）

